name: Docker Workflow
on:
  push:
    paths:
      - '**.java'
  workflow_dispatch:

jobs:
  build_Docker_image:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: clean
        run: mvn -f ~/204_lab7/github-calculator/pom.xml -ntp clean
      - name: Build 
        run: mvn -f ~/204_lab7/github-calculator/pom.xml -ntp compile 
      - name: Short tests
        run: mvn -f ~/204_lab7/github-calculator/pom.xml -ntp tet -Dtest='CalculatorTest'
      - name: Long tests
        run: mvn -f ~/204_lab7/github-calculator/pom.xml -ntp test -Dtest='CalculatorTestThorough'
